10gal: {enabled: true, gpio_number: 4, target: 380, temp_offset: 0, temp_sensor: 28-000004811c44}
20gal: {enabled: false, gpio_number: 4, target: 168, temp_offset: 0, temp_sensor: 28-00000481dd3a}
stick: {enabled: false, gpio_number: 7, target: 152, temp_offset: 0, temp_sensor: 28-0000044ab949}
