10gal: {enabled: false, gpio_number: 5, target: 74, temp_offset: 0, temp_sensor: 28-000004811c44}
20gal: {enabled: true, gpio_number: 6, target: 79, temp_offset: 0, temp_sensor: 28-00000481dd3a}
stick: {enabled: false, gpio_number: 7, target: 5, temp_offset: 0, temp_sensor: 28-49B94A040000}
