stick: {enabled: 'false', gpio_number: 7, target: '0', temp_offset: 0, temp_sensor: 28-49B94A040000}
tengal: {enabled: 'true', gpio_number: 4, target: '0', temp_offset: 0, temp_sensor: 28-000004811c44}
twentygal: {enabled: 'false', gpio_number: 4, target: '', temp_offset: 0, temp_sensor: 28-00000481dd3a}
